name: Manual Label Sync - üè∑Ô∏è

on:
  workflow_call:
    inputs:
      deleteUnmatched:
        type: boolean
        required: true
        default: false

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Config repository
        uses: actions/checkout@v4
        with:
          repository: SessionsBot/.github
          ref: main
          path: configRepo

      - name: Sync labels - Config file
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const syncLabels = require('./configRepo/.github/scripts/sync-labels.js');
            const deleteUnmatched = '${{ github.event.inputs.deleteUnmatched }}' === 'true';
            await syncLabels({ github, context, core }, deleteUnmatched);

      - name: Sync labels - Config file
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('‚úÖ Yay! This job has completed successfully!')
